before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: n96vLeZslcaaaFI+nq2U7EyFR9txzMaHm7PvF8r7TejryF+OIQx/Vnu1G+ff3VjY6kBWqeMEEEKivNCIRjvEooG1DWrgHaaCNH9ugNXva5HzENeHshdWeDaA8LSvWjpr5+sBhvZLFJaVe+0yNOWLJYa8C6sN37bNFEiKSzKPQsfdLJKXfcINJ2ISCK167nBKNspLVouqJPQoZxeBUcjSe94kx7YbSA10vUj3xAesAdd5O6AdTr6ZUoKRxEu+NO0h/K504qysFagOwpTN3SDXqSNDFf7N72XPlHgBrVlmeOiB+gl+imGDf+e8+EoodmLu2V0bldce/M7sM1foVihwXowS5jMHKpGG5If4WghTOUaYvltvfYPJkhi5bdQWj0liWI27l4PnwHEjSjNcjxF34UVtaXgJA5s8II79pp3DZlE4NhtPzggyK1/A3BkNkZZOqg8VpYtbRBEftoQtly4U9MepabM3ZTehNSeCeBawxktIQS05Bycu5hjcqEhBLflMkZ085hGW6azaefdYK6FxBRsogdx0g4AOcmXOnp2e3UyvBA2aF6C//m6YNcJFwQFGeH6IYpp8XCKaifoCu+eFU94s35QvM6c5noVR779jDofmsccWetu3oabqJ69B26NdtqOBVVSxyqU1eJmt5otg+5du8h+Qvfah8FXbri8jF9U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
